name: railway_caution_viewer
version: 1.0.0+1
description: Train-side app to display caution orders live.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true